name: Gradle Build with UberJAR Artifact

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Assemble Uber Jars
        if: github.ref != 'refs/tags/*'
        run: ./gradlew clean build uberJar
      - name: Build and Assemble Uber Jars
        if: github.ref == 'refs/tags/*'
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}  # Remove the 'refs/tags/' prefix
          ./gradlew clean build uberJar -Pproject_version=$TAG_NAME
      - name: Upload app-socket-server Uber Jar
        uses: actions/upload-artifact@v4
        with:
          name: app-socket-server
          path: app-socket-server/build/libs/app-socket-server-uber-*.jar

      - name: Upload app-socket-client Uber Jar
        uses: actions/upload-artifact@v4
        with:
          name: app-socket-client
          path: app-socket-client/build/libs/app-socket-client-uber-*.jar

      - name: Upload app-http-server Uber Jar
        uses: actions/upload-artifact@v4
        with:
          name: app-http-server
          path: app-http-server/build/libs/app-http-server-uber-*.jar

      - name: Upload app-http-client Uber Jar
        uses: actions/upload-artifact@v4
        with:
          name: app-http-client
          path: app-http-client/build/libs/app-http-client-uber-*.jar

      - name: Upload app-standalone Uber Jar
        uses: actions/upload-artifact@v4
        with:
          name: app-standalone
          path: app-standalone/build/libs/app-standalone-uber-*.jar
